"""Added new Clomn in InvoiceItem

Revision ID: 17ffaebd74b1
Revises: 2f27c0e2b9bc
Create Date: 2024-12-10 12:19:31.122008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ffaebd74b1'
down_revision = '2f27c0e2b9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###
