"""date and purchase column added

Revision ID: 185cf10b863c
Revises: 
Create Date: 2024-12-14 11:13:31.365822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '185cf10b863c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###
