"""Added new column to User

Revision ID: 529e1ccbf29f
Revises: 
Create Date: 2024-11-24 15:16:22.029001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529e1ccbf29f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
